// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package entity

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Event) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "idempotency_id":
			z.IdempotencyID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "IdempotencyID")
				return
			}
		case "sensor":
			z.Sensor, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Sensor")
				return
			}
		case "val":
			z.Value, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Value")
				return
			}
		case "ts":
			z.UnixTimestamp, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "UnixTimestamp")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Event) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "idempotency_id"
	err = en.Append(0x84, 0xae, 0x69, 0x64, 0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.IdempotencyID)
	if err != nil {
		err = msgp.WrapError(err, "IdempotencyID")
		return
	}
	// write "sensor"
	err = en.Append(0xa6, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72)
	if err != nil {
		return
	}
	err = en.WriteString(z.Sensor)
	if err != nil {
		err = msgp.WrapError(err, "Sensor")
		return
	}
	// write "val"
	err = en.Append(0xa3, 0x76, 0x61, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Value)
	if err != nil {
		err = msgp.WrapError(err, "Value")
		return
	}
	// write "ts"
	err = en.Append(0xa2, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.UnixTimestamp)
	if err != nil {
		err = msgp.WrapError(err, "UnixTimestamp")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Event) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "idempotency_id"
	o = append(o, 0x84, 0xae, 0x69, 0x64, 0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x69, 0x64)
	o = msgp.AppendString(o, z.IdempotencyID)
	// string "sensor"
	o = append(o, 0xa6, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72)
	o = msgp.AppendString(o, z.Sensor)
	// string "val"
	o = append(o, 0xa3, 0x76, 0x61, 0x6c)
	o = msgp.AppendInt(o, z.Value)
	// string "ts"
	o = append(o, 0xa2, 0x74, 0x73)
	o = msgp.AppendInt64(o, z.UnixTimestamp)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Event) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "idempotency_id":
			z.IdempotencyID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "IdempotencyID")
				return
			}
		case "sensor":
			z.Sensor, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Sensor")
				return
			}
		case "val":
			z.Value, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Value")
				return
			}
		case "ts":
			z.UnixTimestamp, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UnixTimestamp")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Event) Msgsize() (s int) {
	s = 1 + 15 + msgp.StringPrefixSize + len(z.IdempotencyID) + 7 + msgp.StringPrefixSize + len(z.Sensor) + 4 + msgp.IntSize + 3 + msgp.Int64Size
	return
}
