// Code generated by MockGen. DO NOT EDIT.
// Source: dependencies.go
//
// Generated by this command:
//
//	mockgen -source=dependencies.go -destination=mock_journal_test.go -package=sink
//

// Package sink is a generated GoMock package.
package sink

import (
	journal "github.com/andriibeee/iotdemo/pkg/journal"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockJournal is a mock of Journal interface.
type MockJournal struct {
	ctrl     *gomock.Controller
	recorder *MockJournalMockRecorder
	isgomock struct{}
}

// MockJournalMockRecorder is the mock recorder for MockJournal.
type MockJournalMockRecorder struct {
	mock *MockJournal
}

// NewMockJournal creates a new mock instance.
func NewMockJournal(ctrl *gomock.Controller) *MockJournal {
	mock := &MockJournal{ctrl: ctrl}
	mock.recorder = &MockJournalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJournal) EXPECT() *MockJournalMockRecorder {
	return m.recorder
}

// Write mocks base method.
func (m *MockJournal) Write(k, v []byte) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", k, v)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MockJournalMockRecorder) Write(k, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockJournal)(nil).Write), k, v)
}

// WriteBatch mocks base method.
func (m *MockJournal) WriteBatch(entries []journal.Entry) ([]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteBatch", entries)
	ret0, _ := ret[0].([]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteBatch indicates an expected call of WriteBatch.
func (mr *MockJournalMockRecorder) WriteBatch(entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteBatch", reflect.TypeOf((*MockJournal)(nil).WriteBatch), entries)
}
